version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: piggyb
      POSTGRES_PASSWORD: piggyb
    ports:
        - "5432:5432"
