default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  database: piggyb
  username: piggyb
  password: piggyb

development:
  <<: *default
  database: piggyb_development

test:
  <<: *default
  database: piggyb_test

production:
  <<: *default
  database: piggyb
